create proc MyRestore
@pathfile nvarchar(500)
As
ALTER DATABASE MatabDB SET OFFLINE WITH ROLLBACK IMMEDIATE
RESTORE DATABASE MatabDB FROM DISK =@pathfile WITH REPLACE
ALTER DATABASE MatabDB SET ONLINE
GO